const CACHE_NAME = "brevet-sprint-v1.1.20";
const CORE_ASSETS = [
  ".",
  "index.html",
  "styles.css",
  "app.js",
  "version.json",
  "manifest.webmanifest",
  "data/annales.js",
  "data/content.js",
  "data/extra-content-2.js",
  "data/extra-content-3.js",
  "data/extra-content-4.js",
  "data/extra-content-5.js",
  "data/extra-content-6.js",
  "data/extra-content-7.js",
  "data/extra-content-8.js",
  "data/extra-content-9.js",
  "data/extra-content-10.js",
  "data/extra-content-11.js",
  "data/extra-content-12.js",
  "data/extra-content-13.js",
  "data/extra-content.js",
  "data/notions.js",
  "generators/french-language.js",
  "generators/math-calcul.js",
  "generators/registry.js",
  "generators/science-calcul.js",
  "assets/badges/badge-annales-bronze.webp",
  "assets/badges/badge-annales-gold.webp",
  "assets/badges/badge-annales-locked.webp",
  "assets/badges/badge-annales-silver.webp",
  "assets/badges/badge-chapter-bronze.webp",
  "assets/badges/badge-chapter-gold.webp",
  "assets/badges/badge-chapter-locked.webp",
  "assets/badges/badge-chapter-silver.webp",
  "assets/badges/badge-guided-bronze.webp",
  "assets/badges/badge-guided-gold.webp",
  "assets/badges/badge-guided-locked.webp",
  "assets/badges/badge-guided-silver.webp",
  "assets/badges/badge-perfect-bronze.webp",
  "assets/badges/badge-perfect-gold.webp",
  "assets/badges/badge-perfect-locked.webp",
  "assets/badges/badge-perfect-silver.webp",
  "assets/badges/badge-questions-bronze.webp",
  "assets/badges/badge-questions-gold.webp",
  "assets/badges/badge-questions-locked.webp",
  "assets/badges/badge-questions-silver.webp",
  "assets/badges/badge-repairs-bronze.webp",
  "assets/badges/badge-repairs-gold.webp",
  "assets/badges/badge-repairs-locked.webp",
  "assets/badges/badge-repairs-silver.webp",
  "assets/badges/badge-sessions-bronze.webp",
  "assets/badges/badge-sessions-gold.webp",
  "assets/badges/badge-sessions-locked.webp",
  "assets/badges/badge-sessions-silver.webp",
  "assets/badges/badge-stage-discovery-bronze.webp",
  "assets/badges/badge-stage-discovery-gold.webp",
  "assets/badges/badge-stage-discovery-locked.webp",
  "assets/badges/badge-stage-discovery-silver.webp",
  "assets/badges/badge-stage-exam-bronze.webp",
  "assets/badges/badge-stage-exam-gold.webp",
  "assets/badges/badge-stage-exam-locked.webp",
  "assets/badges/badge-stage-exam-silver.webp",
  "assets/badges/badge-stage-training-bronze.webp",
  "assets/badges/badge-stage-training-gold.webp",
  "assets/badges/badge-stage-training-locked.webp",
  "assets/badges/badge-stage-training-silver.webp",
  "assets/badges/badge-streak-bronze.webp",
  "assets/badges/badge-streak-gold.webp",
  "assets/badges/badge-streak-locked.webp",
  "assets/badges/badge-streak-silver.webp",
  "assets/badges/badge-subject-french-bronze.webp",
  "assets/badges/badge-subject-french-gold.webp",
  "assets/badges/badge-subject-french-locked.webp",
  "assets/badges/badge-subject-french-silver.webp",
  "assets/badges/badge-subject-history-bronze.webp",
  "assets/badges/badge-subject-history-gold.webp",
  "assets/badges/badge-subject-history-locked.webp",
  "assets/badges/badge-subject-history-silver.webp",
  "assets/badges/badge-subject-math-bronze.webp",
  "assets/badges/badge-subject-math-gold.webp",
  "assets/badges/badge-subject-math-locked.webp",
  "assets/badges/badge-subject-math-silver.webp",
  "assets/badges/badge-subject-science-bronze.webp",
  "assets/badges/badge-subject-science-gold.webp",
  "assets/badges/badge-subject-science-locked.webp",
  "assets/badges/badge-subject-science-silver.webp",
  "assets/badges/badge-ultimate-bronze.webp",
  "assets/badges/badge-ultimate-gold.webp",
  "assets/badges/badge-ultimate-locked.webp",
  "assets/badges/badge-ultimate-silver.webp",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/pattern.svg"
];
const ANNALES_ASSETS = [
  "annales/2017-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2017-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2017-brevet-general-epreuve-francais-metropole-sujet-complet.pdf",
  "annales/2017-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2017-brevet-general-epreuve-histoire-geographie-emc-metropole-septembre.pdf",
  "annales/2017-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2017-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2017-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2017-brevet-general-epreuve-sciences-metropole-septembre.pdf",
  "annales/2018-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2018-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2018-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-histoire-geographie-emc-metropole-session-2.pdf",
  "annales/2018-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2018-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2018-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2018-brevet-general-epreuve-technologie-metropole-juin-technologie.pdf",
  "annales/2018-brevet-general-epreuve-technologie-metropole-septembre-technologie.pdf",
  "annales/2019-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2019-brevet-general-corrige-detaille-mathematiques-france-septembre.pdf",
  "annales/2019-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2019-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2019-brevet-general-corrige-ou-bareme-francais-bareme-r-daction-bar-me-volutif-argumentatif.pdf",
  "annales/2019-brevet-general-corrige-ou-bareme-francais-bareme-r-daction-bar-me-volutif-narratif.pdf",
  "annales/2019-brevet-general-corrige-ou-bareme-francais-corrige-corrig-acad-mique-complet.pdf",
  "annales/2019-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2019-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2019-brevet-general-epreuve-mathematiques-metropole-secours.pdf",
  "annales/2019-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2019-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2020-brevet-general-corrige-detaille-mathematiques-france-septembre.pdf",
  "annales/2020-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2020-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2020-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2020-brevet-general-epreuve-technologie-metropole-septembre-technologie.pdf",
  "annales/2021-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2021-brevet-general-corrige-detaille-mathematiques-france-septembre.pdf",
  "annales/2021-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2021-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2021-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2021-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2021-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2021-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2021-brevet-general-epreuve-histoire-geographie-emc-metropole-session-4.pdf",
  "annales/2021-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2021-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2021-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2021-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2022-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2022-brevet-general-corrige-detaille-mathematiques-france-septembre.pdf",
  "annales/2022-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2022-brevet-general-corrige-mathematiques-metropole-secours.pdf",
  "annales/2022-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2022-brevet-general-corrige-ou-bareme-francais-corrige-l-ments-de-correction.pdf",
  "annales/2022-brevet-general-corrige-technologie-metropole-juin-technologie.pdf",
  "annales/2022-brevet-general-corrige-technologie-metropole-septembre-technologie.pdf",
  "annales/2022-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-histoire-geographie-emc-metropole-session-2.pdf",
  "annales/2022-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2022-brevet-general-epreuve-mathematiques-metropole-secours.pdf",
  "annales/2022-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2022-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2022-brevet-general-epreuve-technologie-metropole-juin-technologie.pdf",
  "annales/2022-brevet-general-epreuve-technologie-metropole-septembre-technologie.pdf",
  "annales/2023-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2023-brevet-general-corrige-detaille-mathematiques-france-septembre.pdf",
  "annales/2023-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2023-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2023-brevet-general-corrige-ou-bareme-francais-bareme-sujet-de-r-flexion-chelles-descriptives.pdf",
  "annales/2023-brevet-general-corrige-ou-bareme-francais-bareme-sujet-d-imagination-chelles-descriptives.pdf",
  "annales/2023-brevet-general-corrige-ou-bareme-francais-corrige-corrig-acad-mique-synth-tique.pdf",
  "annales/2023-brevet-general-corrige-ou-bareme-francais-corrige-corrig-national.pdf",
  "annales/2023-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-francais-dictee-amenagee-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-francais-dictee-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-francais-grammaire-comprehension-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-francais-redaction-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-histoire-geographie-emc-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2023-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2023-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2023-brevet-general-epreuve-sciences-metropole-septembre.pdf",
  "annales/2024-brevet-general-bareme-technologie-metropole-juin-la-vigie.pdf",
  "annales/2024-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2024-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2024-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2024-brevet-general-corrige-ou-bareme-francais-corrige-dipl-me-national-du-brevet-2024-fran-ais-l-ments-de-correction.pdf",
  "annales/2024-brevet-general-corrige-technologie-metropole-juin-la-vigie.pdf",
  "annales/2024-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-francais-dictee-metropole-septembre.pdf",
  "annales/2024-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-francais-grammaire-comprehension-metropole-septembre.pdf",
  "annales/2024-brevet-general-epreuve-francais-metropole-dictee.pdf",
  "annales/2024-brevet-general-epreuve-francais-metropole-dictee-amenagee.pdf",
  "annales/2024-brevet-general-epreuve-francais-metropole-grammaire-comprehension.pdf",
  "annales/2024-brevet-general-epreuve-francais-metropole-redaction.pdf",
  "annales/2024-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-francais-redaction-metropole-septembre.pdf",
  "annales/2024-brevet-general-epreuve-histoire-geographie-emc-metropole.pdf",
  "annales/2024-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-histoire-geographie-emc-metropole-session-4.pdf",
  "annales/2024-brevet-general-epreuve-mathematiques-metropole.pdf",
  "annales/2024-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2024-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2024-brevet-general-epreuve-mathematiques-metropole-septembre-2.pdf",
  "annales/2024-brevet-general-epreuve-sciences-metropole.pdf",
  "annales/2024-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2024-brevet-general-epreuve-sciences-metropole-septembre.pdf",
  "annales/2024-brevet-general-epreuve-technologie-metropole-juin-la-vigie.pdf",
  "annales/2025-brevet-general-corrige-detaille-mathematiques-france-juin.pdf",
  "annales/2025-brevet-general-corrige-francais.pdf",
  "annales/2025-brevet-general-corrige-histoire-geographie-emc.pdf",
  "annales/2025-brevet-general-corrige-mathematiques.pdf",
  "annales/2025-brevet-general-corrige-mathematiques-metropole-juin.pdf",
  "annales/2025-brevet-general-corrige-mathematiques-metropole-septembre.pdf",
  "annales/2025-brevet-general-corrige-ou-bareme-francais-corrige-dipl-me-national-du-brevet-session-2025-s-rie-g-n-rale-fran-ais-l-ments.pdf",
  "annales/2025-brevet-general-corrige-sciences.pdf",
  "annales/2025-brevet-general-epreuve-francais-dictee.pdf",
  "annales/2025-brevet-general-epreuve-francais-dictee-amenagee-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-francais-dictee-amenagee-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-francais-dictee-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-francais-dictee-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-francais-grammaire-comprehension-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-francais-grammaire-comprehension-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-francais-redaction-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-francais-redaction-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-francais-sujet-complet.pdf",
  "annales/2025-brevet-general-epreuve-histoire-geographie-emc.pdf",
  "annales/2025-brevet-general-epreuve-histoire-geographie-emc-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-histoire-geographie-emc-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-mathematiques.pdf",
  "annales/2025-brevet-general-epreuve-mathematiques-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-mathematiques-metropole-juin-2.pdf",
  "annales/2025-brevet-general-epreuve-mathematiques-metropole-septembre.pdf",
  "annales/2025-brevet-general-epreuve-mathematiques-metropole-septembre-2.pdf",
  "annales/2025-brevet-general-epreuve-sciences.pdf",
  "annales/2025-brevet-general-epreuve-sciences-metropole-juin.pdf",
  "annales/2025-brevet-general-epreuve-sciences-metropole-septembre.pdf",
  "annales/2026-brevet-corrige-mathematiques-sujet-0-a.pdf",
  "annales/2026-brevet-corrige-mathematiques-sujet-0-b.pdf",
  "annales/2026-brevet-epreuve-mathematiques-sujet-0-a.pdf",
  "annales/2026-brevet-epreuve-mathematiques-sujet-0-b.pdf",
  "annales/2026-brevet-general-corrige-detaille-mathematiques-france-metropole-juin.pdf",
  "annales/2026-brevet-general-corrige-detaille-mathematiques-france-sujet-0-a.pdf",
  "annales/2026-brevet-general-corrige-detaille-mathematiques-france-sujet-0-b.pdf",
  "annales/2026-brevet-general-epreuve-francais-metropole-dictee.pdf",
  "annales/2026-brevet-general-epreuve-francais-metropole-dictee-amenagee.pdf",
  "annales/2026-brevet-general-epreuve-francais-metropole-grammaire-comprehension.pdf",
  "annales/2026-brevet-general-epreuve-francais-metropole-redaction.pdf",
  "annales/2026-brevet-general-epreuve-histoire-geographie-emc-metropole.pdf",
  "annales/2026-brevet-general-epreuve-mathematiques-metropole.pdf",
  "annales/2026-brevet-general-epreuve-mathematiques-sujet-0-a-eduscol.pdf",
  "annales/2026-brevet-general-epreuve-mathematiques-sujet-0-b-eduscol.pdf",
  "annales/2026-brevet-general-epreuve-sciences-metropole.pdf"
];

const ALL_ASSETS = [...CORE_ASSETS, ...ANNALES_ASSETS];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(ALL_ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).then((response) => {
        const copy = response.clone();
        caches.open(CACHE_NAME).then((cache) => cache.put("index.html", copy));
        return response;
      }).catch(() => caches.match("index.html"))
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => cached || fetch(request).then((response) => {
      const copy = response.clone();
      caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
      return response;
    }).catch(() => caches.match("index.html")))
  );
});

